title: Hair's Your Answer
baseurl: /
permalink: "/:title/"
collections:
  posts:
    permalink: "/posts/:title/"
description: Hair's Your Answer is Erie’s finest hair-restoration studio offering proven solutions to hair-loss.
header:
  title: Hair's Your Answer
  has_nav: true
  nav_links:
    - label: Home
      url: /
      new_window: false
    - label: About Us
      url: /about/
      new_window: false
    - label: Hair Restoration for Men
      url: /hair-restoration-for-men/
      new_window: false
    - label: Hair Restoration for Women
      url: /hair-restoration-for-women/
      new_window: false
    - label: Laser Therapy
      url: /hair-laser-therapy/
      new_window: false
    - label: FAQ
      url: /hair-restoration-faq/
      new_window: false
footer:
  content: "&copy; Hair's Your Answer 2020. All rights reserved."
  links:
    - label: Made with Stackbit
      url: "https://www.stackbit.com"
      new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: "https://twitter.com/"
      new_window: true
    - label: Instagram
      url: "https://www.instagram.com/"
      new_window: true
    - label: LinkedIn
      url: "https://www.linkedin.com/"
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
